{% set name = "pyDOE3" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 33923da2aa04ce0381a8fe9db678cba0c4b9906290a0c38dbf9cf316845ec98e


build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs

  run:
    - python >={{ python_min }}
    - scipy
    - numpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyDOE3

about:
  home: https://github.com/relf/pyDOE3
  summary: 'Simple, fast, extensible JSON encoder/decoder for Python'
  description: Fork of pyDOE2, package designed to help the scientist, engineer, statistician, etc., to construct appropriate experimental designs.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - relf
