{% set name = "pyDOE3" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: e0547d7b919dcd259abd96b91ea56f8d1a41f63efd6f393eacdbc06697d6034e


build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
    - hatch-vcs

  run:
    - python >=3.8
    - scipy
    - numpy

test:
  imports:
    - pyDOE3

about:
  home: https://github.com/relf/pyDOE3
  summary: 'Simple, fast, extensible JSON encoder/decoder for Python'
  description: Fork of pyDOE2, package designed to help the scientist, engineer, statistician, etc., to construct appropriate experimental designs.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - relf
